name: "Release"

on:
  push:
    tags:
      - "*.*.*"

env:
  PROJECT_PATH: PboSpy.sln
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/nuget-packages

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: NuGet cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: >
          dotnet build ${{ env.PROJECT_PATH }} -c Release -o ".\publish" --no-restore
      
      - name: Fetch previous release
        continue-on-error: true
        shell: pwsh
        run: |
          ${{ env.NUGET_PACKAGES }}\clowd.squirrel\2.9.42\tools\Squirrel.exe github-down `
          --repoUrl "https://github.com/rvost/PboSpy"

      - name: Publish
        shell: pwsh
        run: |
          ${{ env.NUGET_PACKAGES }}\clowd.squirrel\2.9.42\tools\Squirrel.exe  pack `
          --framework net6 `
          --packId "PboSpy" `
          --packVersion "${{github.ref_name}}" `
          --packAuthors "rvost" `
          --packDir ".\publish" `
          --icon ".\images\PboSpy.ico" `
          --splashImage ".\images\SplashScreen.png"

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            Releases/RELEASES
            Releases/*.exe
            Releases/*.nupkg
